version: '3'

services:
  node:
    build: .
    container_name: shopper_api
    command: npm run start
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
  db:
    image: mysql:8.0.32
    container_name: shopper_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5